language: ruby

rvm:
  - ruby-head
  - 2.0.0

matrix:
  include:
    - rvm: 2.0.0

branches:
  only:
  - master
  - stable
  - travis

deploy:
  provider: heroku
  app:
    master: bcmaster-dev
    stable: bcmaster
  api_key: b3f1822f-cc5b-459f-a7d6-d13ded0db51d
