language: ruby
rvm:
- jruby-18mode
- jruby-19mode
- jruby-head

# white list
#branches:
#  only:
#  - master
#  - stable

deploy:
  provider: heroku
  app:
    master: bcmaster-dev
    stable: bcmaster
  api_key:
    secure: AJSVxzk7Rho14LjgYibYiAh/w25VJVwAyCpdJ5iR1a21YWKCr6AVCrxXTWMbPdJBxhZj9oDEUS/DcFx0SNamg9cGPN3X0Yv6XaGHWdrpMVOuiuKdTUYhXVhAju9+wq05NWgcc3yqIMpAA/y6AaLRuzrYqjyS5q1uDfnoDe3GddQ=
