language: ruby

rvm:
  - ruby-head
  - 2.0.0

#env:
#  matrix:
#    - DB=postgresql
#    - DB=sqlite
#    - DB=mysql
#  global:
#    - "JRUBY_OPTS=-Xcext.enabled=true" 

#matrix:
#  include:
#    - rvm: jruby-19mode
#      env: DB=sqlite

# white list
#branches:
#  only:
#  - master
#  - stable

#services:
#  - pgsql 

#before_script:
#  - psql -c 'create database myapp_test;' -U postgres

#script:
#  - RAILS_ENV=test bundle exec rake --trace db:migrate test
#  - export RAILS_ENV=test
#  - rake db:test:load
#  - bundle exec rake db:create db:migrate
#  - bundle exec rake db:test:prepare

deploy:
  provider: heroku
  app:
    master: bcmaster-dev
    stable: bcmaster
  api_key: b3f1822f-cc5b-459f-a7d6-d13ded0db51d
